import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Phase 2 — tenancy and identity foundation.
 *
 * Written by hand on purpose: generated migrations do not produce CHECK
 * constraints, composite unique keys or readable index names.
 *
 * Conventions applied here and in every later migration:
 * - CHAR(36) identifiers (UUIDv7, generated by the application).
 * - DATETIME(3) in UTC; the connection runs with timezone 'Z'.
 * - InnoDB + utf8mb4.
 * - Foreign keys are RESTRICT by default; CASCADE only inside an aggregate.
 */
export class InitTenancyAndIdentity1789674597432 implements MigrationInterface {
  name = 'InitTenancyAndIdentity1789674597432';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE \`tenants\` (
        \`id\` CHAR(36) NOT NULL,
        \`name\` VARCHAR(120) NOT NULL,
        \`slug\` VARCHAR(60) NOT NULL,
        \`business_type\` ENUM('BARBERSHOP','SALON','SPA','CLINIC','DENTAL','TATTOO','OTHER')
          NOT NULL DEFAULT 'BARBERSHOP',
        \`country\` CHAR(2) NOT NULL,
        \`currency\` CHAR(3) NOT NULL,
        \`timezone\` VARCHAR(64) NOT NULL,
        \`phone\` VARCHAR(20) NULL,
        \`email\` VARCHAR(160) NULL,
        \`status\` ENUM('ACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
        \`created_at\` DATETIME(3) NOT NULL,
        \`updated_at\` DATETIME(3) NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE INDEX \`uq_tenants_slug\` (\`slug\`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
    `);

    await queryRunner.query(`
      CREATE TABLE \`users\` (
        \`id\` CHAR(36) NOT NULL,
        \`email\` VARCHAR(160) NOT NULL,
        \`password_hash\` VARCHAR(255) NOT NULL,
        \`name\` VARCHAR(120) NOT NULL,
        \`created_at\` DATETIME(3) NOT NULL,
        \`updated_at\` DATETIME(3) NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE INDEX \`uq_users_email\` (\`email\`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
    `);

    await queryRunner.query(`
      CREATE TABLE \`memberships\` (
        \`id\` CHAR(36) NOT NULL,
        \`tenant_id\` CHAR(36) NOT NULL,
        \`user_id\` CHAR(36) NOT NULL,
        \`role\` ENUM('OWNER','ADMIN','STAFF') NOT NULL,
        \`status\` ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
        \`created_at\` DATETIME(3) NOT NULL,
        \`updated_at\` DATETIME(3) NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE INDEX \`uq_memberships_tenant_user\` (\`tenant_id\`, \`user_id\`),
        INDEX \`ix_memberships_user\` (\`user_id\`),
        CONSTRAINT \`fk_memberships_tenant\` FOREIGN KEY (\`tenant_id\`)
          REFERENCES \`tenants\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_memberships_user\` FOREIGN KEY (\`user_id\`)
          REFERENCES \`users\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
    `);

    await queryRunner.query(`
      CREATE TABLE \`refresh_tokens\` (
        \`id\` CHAR(36) NOT NULL,
        \`user_id\` CHAR(36) NOT NULL,
        \`membership_id\` CHAR(36) NOT NULL,
        \`token_hash\` CHAR(64) NOT NULL,
        \`family_id\` CHAR(36) NOT NULL,
        \`expires_at\` DATETIME(3) NOT NULL,
        \`revoked_at\` DATETIME(3) NULL,
        \`replaced_by_id\` CHAR(36) NULL,
        \`created_at\` DATETIME(3) NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE INDEX \`uq_refresh_tokens_token_hash\` (\`token_hash\`),
        INDEX \`ix_refresh_tokens_user\` (\`user_id\`),
        INDEX \`ix_refresh_tokens_family\` (\`family_id\`),
        CONSTRAINT \`fk_refresh_tokens_user\` FOREIGN KEY (\`user_id\`)
          REFERENCES \`users\` (\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT,
        CONSTRAINT \`fk_refresh_tokens_membership\` FOREIGN KEY (\`membership_id\`)
          REFERENCES \`memberships\` (\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE `refresh_tokens`');
    await queryRunner.query('DROP TABLE `memberships`');
    await queryRunner.query('DROP TABLE `users`');
    await queryRunner.query('DROP TABLE `tenants`');
  }
}
